# Generated by Django 4.2.6 on 2023-10-16 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='tpack_name',
            new_name='tourplace',
        ),
        migrations.AddField(
            model_name='tourmoreplaces',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packages',
            name='pack_facility',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
