# Generated by Django 4.2.6 on 2023-10-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_tourmoreplaces_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
