# Generated by Django 4.2.6 on 2023-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tourmoreplaces_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='pack_price',
            field=models.IntegerField(),
        ),
    ]
