# Generated by Django 4.2.6 on 2023-10-30 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_packages_pack_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField()),
                ('b_email', models.EmailField(max_length=254)),
                ('b_members', models.SmallIntegerField()),
                ('b_price', models.IntegerField()),
                ('b_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.packages')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
