# Generated by Django 4.2.6 on 2023-10-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_tourbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourplaces',
            name='cities',
        ),
    ]
