# Generated by Django 4.2.6 on 2023-11-01 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_tourplaces_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_des', models.CharField(default=None, max_length=1000)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('r_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.packages')),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
