# Generated by Django 4.2.6 on 2023-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_reviewpack_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpack',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
    ]
