# Generated by Django 4.2.6 on 2023-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_reviewpack_r_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
